# Generated by Django 5.1.4 on 2025-01-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_bookmark_post_comment_post_like_post_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bookmark',
            field=models.JSONField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='comment',
            field=models.JSONField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.JSONField(default=0),
        ),
    ]
