# Generated by Django 5.1.4 on 2025-01-22 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_bookmark_post_comment_post_like_and_more'),
        ('posts', '0006_remove_post_user'),
    ]

    operations = [
    ]
