# Generated by Django 5.1.4 on 2025-02-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_name_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MEMBER', 'Member')], default=1, max_length=6),
            preserve_default=False,
        ),
    ]
