# Generated by Django 5.1.4 on 2025-02-07 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MEMBER', 'Member')], default='ADMIN', max_length=6),
            preserve_default=False,
        ),
    ]
