# Generated by Django 5.1.4 on 2025-02-07 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
