# Generated by Django 5.1.4 on 2025-01-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_rename_category_id_community_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='visibility',
            field=models.CharField(choices=[('PB', 'PUBLIC'), ('PV', 'PRIVATE')], default='PB', max_length=2),
        ),
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='community_images/'),
        ),
        migrations.AlterField(
            model_name='community',
            name='max_members',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
