# Generated by Django 5.1.4 on 2025-01-17 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0007_community_visibility_alter_community_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=7),
        ),
    ]
