# Generated by Django 5.1.4 on 2025-01-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0008_alter_community_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='image',
            field=models.ImageField(null=True, upload_to='images/communities'),
        ),
    ]
