# Generated by Django 5.1.4 on 2025-01-17 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0010_alter_community_max_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='user',
        ),
    ]
