# Generated by Django 5.1.4 on 2025-02-07 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0012_community_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='user',
        ),
    ]
