# Generated by Django 5.1.4 on 2025-02-07 03:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0013_remove_community_user'),
        ('roles', '0002_alter_role_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='members',
        ),
        migrations.AddField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(related_name='joined_communities', through='roles.Role', to=settings.AUTH_USER_MODEL),
        ),
    ]
