# Generated by Django 5.1.4 on 2025-02-07 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0014_remove_community_members_community_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='members',
        ),
    ]
