# Generated by Django 5.1.4 on 2025-02-18 14:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0015_remove_community_members'),
        ('roles', '0004_alter_role_unique_together_remove_role_community'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(related_name='joined_communities', through='roles.Role', to=settings.AUTH_USER_MODEL),
        ),
    ]
