# Generated by Django 5.1.4 on 2025-02-06 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        ('communities', '0011_remove_community_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='community',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='communities.community'),
            preserve_default=False,
        ),
    ]
