# Generated by Django 5.1.4 on 2025-02-07 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0014_remove_community_members_community_members'),
        ('roles', '0002_alter_role_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.community'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('user', 'community')},
        ),
    ]
