# Generated by Django 5.1.4 on 2025-02-07 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_alter_role_community_alter_role_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='role',
            name='community',
        ),
    ]
