# Generated by Django 5.1.4 on 2025-02-18 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0016_community_members'),
        ('roles', '0004_alter_role_unique_together_remove_role_community'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='community',
            field=models.ForeignKey(default=34, on_delete=django.db.models.deletion.CASCADE, to='communities.community'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('user', 'community')},
        ),
    ]
